### ISSUE TITLE
Bottom Nav Bar does not show if there are four or more items

### ISSUE THREAD

**Issue by jaxondu** [mjohnsullivan/flutter-by-example#5]
Trying out this example:

https://github.com/mjohnsullivan/flutter-by-example/tree/master/13_bottom_nav_bar

When I add in two more BottomNavigationBarItem to four, the bottom navigation bar does not display on the screen but you can still tap on it to navigate through the various Offstage widget.

**Comment by mjohnsullivan** [comment]
Never tried more than three; I'll take a look into it.

**Comment by mjohnsullivan** [comment]
Turns out that when there's more than 3 items in the nav bar, it changes it's type from fixed to shifting, and shifting, and shifting renders items in white:

https://docs.flutter.io/flutter/material/BottomNavigationBar-class.html

I'll update the sample to talk about this and give an example of how it's handled.
